Kan 36 feat double tab teleport
SEOKMINJUN/Invaders-SDP pull request #18
Opened 2024-11-16 16:35 UTC by RyuJeMu

## What
This PR implements the double-tap teleport functionality for the Ship in the game. It includes the following changes:
- Added double-tap detection logic to the `InputManager`.
- Modified the `Ship` class to handle teleportation to screen edges on double-tap (left or right arrow keys).
- Ensured the Ship does not exceed screen boundaries during teleportation.
- Logged teleportation events for debugging and verification.

## Why
This feature enhances game-play by adding a unique teleportation mechanic, making the player's movement more dynamic and strategic.

## How to Test
1. Start the game locally.
2. Use the left arrow key (`KEY_LEFT`) to perform a double-tap. Verify the Ship teleports to the left edge of the screen.
3. Use the right arrow key (`KEY_RIGHT`) to perform a double-tap. Verify the Ship teleports to the right edge of the screen.
4. Ensure that the Ship does not move outside the screen boundaries during teleportation.
5. Check the logs to confirm teleportation events are correctly logged.

## Additional Information
- This feature was thoroughly tested with various edge cases, such as rapid key presses and edge boundary handling.
- Future extensions could include cooldown mechanics or visual feedback for teleportation events.

2024-11-17 10:17 UTC, SEOKMINJUN requested changes

2024-11-17 10:17 UTC, SEOKMINJUN commented on src/engine/InputManager.java
> +		lastKeyPress.put(keyCode, currentTime);
lastPressTime should be updated at the start of input, not during pressing a key.
It always detect double tap when just pressing key

2024-11-17 10:17 UTC, SEOKMINJUN commented on src/entity/Ship.java
> +			if (inputManager.isKeyDown(KEY_RIGHT) && !isRightBorder) {
It can't detect double tap

2024-11-17 10:17 UTC, SEOKMINJUN commented on src/entity/Ship.java
> +			if (inputManager.isKeyDown(KEY_LEFT) && !isLeftBorder) {
It can't detect double tap also

2024-11-18 04:19 UTC, RyuJeMu commented
Resolved the issue of continuous key press detection using a boolean flag and ensured the functionality works only for the same key.

2024-11-18 04:56 UTC, SEOKMINJUN requested changes

2024-11-18 04:56 UTC, SEOKMINJUN commented on src/engine/InputManager.java
> +		if (keyCode != KeyEvent.VK_LEFT && keyCode != KeyEvent.VK_RIGHT) { return false; }
It makes player 2 can't use double tap feature
And it will not works in future when ship's movement key gonna be changed.

2024-11-18 04:56 UTC, SEOKMINJUN commented on src/engine/InputManager.java
> +	private Set<Integer> pressedKeys = new HashSet<>();
It not used, only holding pressed key

2024-11-18 04:56 UTC, SEOKMINJUN commented on src/engine/InputManager.java
> +				(currentTime - lastPressTime > 0) &&
This is always true

2024-11-18 04:56 UTC, SEOKMINJUN commented on src/engine/InputManager.java
> +			boolean isDoubleTap = (currentTime - lastTime) > DOUBLE_TAP_THRESHOLD;
How about save isDoubleTap into map?

2024-11-18 04:56 UTC, SEOKMINJUN commented on src/engine/InputManager.java
> +				(currentTime - lastPressTime <= DOUBLE_TAP_THRESHOLD);
This section detect key press in 300 milliseconds instead of double tap.
I think this line will be useful in KeyPressed function.

2024-11-18 06:52 UTC, closed without merging

2024-11-18 11:26 UTC, DongjunSuh923 approved these changes