Kan 36 feat double tab teleport
SEOKMINJUN/Invaders-SDP pull request #20
Opened 2024-11-21 04:20 UTC by RyuJeMu

## What  
This PR adds enhancements and fixes related to the teleportation feature and cooldown display. It includes the following changes:  
- **Handled Key Holding:** Implemented an exception to ensure teleportation does not trigger while holding down a key.  
- **Teleport Cooldown:** Adjusted the teleportation cooldown time to 3.5 seconds.  
- **Cooldown Display:** Added a visual representation of the cooldown on the screen, including a countdown timer inside a circular indicator.  
- **Double-Tap Teleportation:** Enabled teleportation to the edges of the screen when double-tapping the respective direction keys.  
- **Distance Calculation:** Distance calculation is currently non-functional and will be addressed in a future update.  

## Why  
The teleportation feature required fine-tuning to improve usability and visual feedback. These changes ensure a smoother and more user-friendly experience, while avoiding unintended behavior such as triggering actions while holding down keys.  

## How to Test  
1. **Test Key Holding Exception:**  
   - Press and hold the right or left directional key and ensure that teleportation is not triggered.  

2. **Test Cooldown Display:**  
   - Perform a double-tap teleportation.  
   - Verify that a cooldown circle with a countdown timer appears on the screen, preventing immediate reuse of the teleport feature.  

3. **Test Cooldown Timing:**  
   - Wait for 3.5 seconds after teleportation and ensure that the feature becomes available again.  

4. **Test Edge Teleportation:**  
   - Double-tap the left key and confirm the player teleports to the left edge of the screen.  
   - Double-tap the right key and confirm the player teleports to the right edge of the screen.  

5. **Test Distance Calculation:**  
   - Attempt to calculate the distance moved by the player. Note that this feature is currently non-functional.

2024-11-21 07:27 UTC, SEOKMINJUN requested changes

2024-11-21 07:27 UTC, SEOKMINJUN commented on src/screen/GameScreen.java
> +			if (Globals.getInputManager().isDoubleTab(KeyEvent.VK_RIGHT) && doubleTapCooldown.getRemainingTime() == 0 ) {
This is not handle ship's key setting.
And ship's movement is out of there class. This is should be in ship class

2024-11-21 07:27 UTC, SEOKMINJUN commented on src/screen/GameScreen.java
> +			if (Globals.getInputManager().isDoubleTab(KeyEvent.VK_LEFT) && doubleTapCooldown.getRemainingTime() == 0) {
same here too

2024-11-22 05:21 UTC, RyuJeMu commented on src/entity/Ship.java
> +	}
I add detectedDoublTap() in Ship.java. Teleport-function was executed successfully.

2024-11-22 12:35 UTC, SEOKMINJUN approved these changes

2024-11-24 02:50 UTC, HanRH99 approved these changes

2024-11-24 05:11 UTC, merged